export const HANDLE_STATE = "HANDLE_STATE";
export const RESET_FORM = "RESET_FORM";
export const ERRORS_MESSAGE = "ERRORS_MESSAGE";
export const LOADING = 'LOADING';
export const REQUEST_CURRENCIES_STARTED = 'REQUEST_CURRENCIES_STARTED';
export const REQUEST_CURRENCIES_SUCCESSFULL = 'REQUEST_CURRENCIES_SUCCESSFULL';
export const REQUEST_CURRENCIES_FAILED = 'REQUEST_CURRENCIES_FAILED';